#ifndef NAGE_ENGINE_WORLD_PROCEDURAL_SIMPLEX_NOISE_H_
#define NAGE_ENGINE_WORLD_PROCEDURAL_SIMPLEX_NOISE_H_

namespace NAGE
{
    // TODO
    class SimplexNoise
    {

    };
}

#endif // NAGE_ENGINE_WORLD_PROCEDURAL_SIMPLEX_NOISE_H_
